POST http://localhost:9000/users HTTP/1.1
content-type: application/json

{
    "username": "zszssisxn.it.desvx",
    "email": "xzisn.issst.xdes@gmail.com",
    "password": "13456",
    "firstName": "sZIN",
    "lastName": "Lee",
    "avatar": ""
}

###

POST http://localhost:9000/users/token HTTP/1.1
content-type: application/json

{
    "email": "zin.it.dev@gmail.com",
    "password": "12345"
}